#ifndef REP_MYLOG_REPLICA_H
#define REP_MYLOG_REPLICA_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectpendingcall.h>
#include <QtRemoteObjects/qremoteobjectreplica.h>


class myLogReplica : public QRemoteObjectReplica
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "myLog")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "82622c9d66c741d23b058105a0bab9bd13df9a9a")
    Q_PROPERTY(int heartBeatInterval READ heartBeatInterval NOTIFY heartBeatIntervalChanged)
    Q_PROPERTY(bool isWriteToFile READ isWriteToFile NOTIFY isWriteToFileChanged)
    Q_PROPERTY(int maxLogCount READ maxLogCount NOTIFY maxLogCountChanged)
    Q_PROPERTY(int maxFileSize READ maxFileSize NOTIFY maxFileSizeChanged)
    Q_PROPERTY(QString logDir READ logDir NOTIFY logDirChanged)

public:
    myLogReplica() : QRemoteObjectReplica() { initialize(); }
    static void registerMetatypes()
    {
        static bool initialized = false;
        if (initialized)
            return;
        initialized = true;
        qRegisterMetaType<QRemoteObjectPendingCall>();
        qRegisterMetaType<QRemoteObjectPendingReply<void>>();
        if (!QMetaType::hasRegisteredConverterFunction<QRemoteObjectPendingReply<void>, QRemoteObjectPendingCall>())
            QMetaType::registerConverter<QRemoteObjectPendingReply<void>, QRemoteObjectPendingCall>();

    }

private:
    myLogReplica(QRemoteObjectNode *node, const QString &name = QString())
        : QRemoteObjectReplica(ConstructWithNode)
    {
        initializeNode(node, name);
    }

    void initialize() override
    {
        myLogReplica::registerMetatypes();
        QVariantList properties;
        properties.reserve(5);
        properties << QVariant::fromValue(int(50));
        properties << QVariant::fromValue(bool(false));
        properties << QVariant::fromValue(int(2000));
        properties << QVariant::fromValue(int(30));
        properties << QVariant::fromValue(QString());
        setProperties(properties);
    }

public:
    ~myLogReplica() override = default;

    int heartBeatInterval() const
    {
        const QVariant variant = propAsVariant(0);
        if (!variant.canConvert<int>()) {
            qWarning() << "QtRO cannot convert the property heartBeatInterval to type int";
        }
        return variant.value<int >();
    }

    bool isWriteToFile() const
    {
        const QVariant variant = propAsVariant(1);
        if (!variant.canConvert<bool>()) {
            qWarning() << "QtRO cannot convert the property isWriteToFile to type bool";
        }
        return variant.value<bool >();
    }

    int maxLogCount() const
    {
        const QVariant variant = propAsVariant(2);
        if (!variant.canConvert<int>()) {
            qWarning() << "QtRO cannot convert the property maxLogCount to type int";
        }
        return variant.value<int >();
    }

    int maxFileSize() const
    {
        const QVariant variant = propAsVariant(3);
        if (!variant.canConvert<int>()) {
            qWarning() << "QtRO cannot convert the property maxFileSize to type int";
        }
        return variant.value<int >();
    }

    QString logDir() const
    {
        const QVariant variant = propAsVariant(4);
        if (!variant.canConvert<QString>()) {
            qWarning() << "QtRO cannot convert the property logDir to type QString";
        }
        return variant.value<QString >();
    }


Q_SIGNALS:
    void heartBeatIntervalChanged(int heartBeatInterval);
    void isWriteToFileChanged(bool isWriteToFile);
    void maxLogCountChanged(int maxLogCount);
    void maxFileSizeChanged(int maxFileSize);
    void logDirChanged(QString logDir);
    void logChanged(const QString & data);
    void heartToClient(qint64 time);

public Q_SLOTS:
    void pushHeartBeatInterval(int heartBeatInterval)
    {
        static int __repc_index = myLogReplica::staticMetaObject.indexOfSlot("pushHeartBeatInterval(int)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(heartBeatInterval);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushIsWriteToFile(bool isWriteToFile)
    {
        static int __repc_index = myLogReplica::staticMetaObject.indexOfSlot("pushIsWriteToFile(bool)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(isWriteToFile);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushMaxLogCount(int maxLogCount)
    {
        static int __repc_index = myLogReplica::staticMetaObject.indexOfSlot("pushMaxLogCount(int)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(maxLogCount);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushMaxFileSize(int maxFileSize)
    {
        static int __repc_index = myLogReplica::staticMetaObject.indexOfSlot("pushMaxFileSize(int)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(maxFileSize);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushLogDir(QString logDir)
    {
        static int __repc_index = myLogReplica::staticMetaObject.indexOfSlot("pushLogDir(QString)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(logDir);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void exitServer()
    {
        static int __repc_index = myLogReplica::staticMetaObject.indexOfSlot("exitServer()");
        QVariantList __repc_args;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }

private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};


QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // REP_MYLOG_REPLICA_H
