#ifndef REP_MYLOG_SOURCE_H
#define REP_MYLOG_SOURCE_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectsource.h>


class myLogSource : public QObject
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "myLog")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "82622c9d66c741d23b058105a0bab9bd13df9a9a")
    Q_PROPERTY(int heartBeatInterval READ heartBeatInterval WRITE setHeartBeatInterval NOTIFY heartBeatIntervalChanged)
    Q_PROPERTY(bool isWriteToFile READ isWriteToFile WRITE setIsWriteToFile NOTIFY isWriteToFileChanged)
    Q_PROPERTY(int maxLogCount READ maxLogCount WRITE setMaxLogCount NOTIFY maxLogCountChanged)
    Q_PROPERTY(int maxFileSize READ maxFileSize WRITE setMaxFileSize NOTIFY maxFileSizeChanged)
    Q_PROPERTY(QString logDir READ logDir WRITE setLogDir NOTIFY logDirChanged)

public:
    explicit myLogSource(QObject *parent = nullptr) : QObject(parent)
    {
    }

public:
    ~myLogSource() override = default;

    virtual int heartBeatInterval() const = 0;
    virtual bool isWriteToFile() const = 0;
    virtual int maxLogCount() const = 0;
    virtual int maxFileSize() const = 0;
    virtual QString logDir() const = 0;
    virtual void setHeartBeatInterval(int heartBeatInterval) = 0;
    virtual void setIsWriteToFile(bool isWriteToFile) = 0;
    virtual void setMaxLogCount(int maxLogCount) = 0;
    virtual void setMaxFileSize(int maxFileSize) = 0;
    virtual void setLogDir(QString logDir) = 0;

Q_SIGNALS:
    void heartBeatIntervalChanged(int heartBeatInterval);
    void isWriteToFileChanged(bool isWriteToFile);
    void maxLogCountChanged(int maxLogCount);
    void maxFileSizeChanged(int maxFileSize);
    void logDirChanged(QString logDir);
    void logChanged(const QString & data);
    void heartToClient(qint64 time);

public Q_SLOTS:
    virtual void pushHeartBeatInterval(int heartBeatInterval)
    {
        setHeartBeatInterval(heartBeatInterval);
    }
    virtual void pushIsWriteToFile(bool isWriteToFile)
    {
        setIsWriteToFile(isWriteToFile);
    }
    virtual void pushMaxLogCount(int maxLogCount)
    {
        setMaxLogCount(maxLogCount);
    }
    virtual void pushMaxFileSize(int maxFileSize)
    {
        setMaxFileSize(maxFileSize);
    }
    virtual void pushLogDir(QString logDir)
    {
        setLogDir(logDir);
    }
    virtual void exitServer() = 0;

private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};


class myLogSimpleSource : public myLogSource
{
    Q_OBJECT

public:
    explicit myLogSimpleSource(QObject *parent = nullptr) : myLogSource(parent)
    , m_heartBeatInterval(50)
    , m_isWriteToFile(false)
    , m_maxLogCount(2000)
    , m_maxFileSize(30)
    , m_logDir()
    {
    }

public:
    ~myLogSimpleSource() override = default;

    int heartBeatInterval() const override { return m_heartBeatInterval; }
    bool isWriteToFile() const override { return m_isWriteToFile; }
    int maxLogCount() const override { return m_maxLogCount; }
    int maxFileSize() const override { return m_maxFileSize; }
    QString logDir() const override { return m_logDir; }
    void setHeartBeatInterval(int heartBeatInterval) override
    {
        if (heartBeatInterval != m_heartBeatInterval) {
            m_heartBeatInterval = heartBeatInterval;
            Q_EMIT heartBeatIntervalChanged(m_heartBeatInterval);
        }
    }
    void setIsWriteToFile(bool isWriteToFile) override
    {
        if (isWriteToFile != m_isWriteToFile) {
            m_isWriteToFile = isWriteToFile;
            Q_EMIT isWriteToFileChanged(m_isWriteToFile);
        }
    }
    void setMaxLogCount(int maxLogCount) override
    {
        if (maxLogCount != m_maxLogCount) {
            m_maxLogCount = maxLogCount;
            Q_EMIT maxLogCountChanged(m_maxLogCount);
        }
    }
    void setMaxFileSize(int maxFileSize) override
    {
        if (maxFileSize != m_maxFileSize) {
            m_maxFileSize = maxFileSize;
            Q_EMIT maxFileSizeChanged(m_maxFileSize);
        }
    }
    void setLogDir(QString logDir) override
    {
        if (logDir != m_logDir) {
            m_logDir = logDir;
            Q_EMIT logDirChanged(m_logDir);
        }
    }

private:
    int m_heartBeatInterval;
    bool m_isWriteToFile;
    int m_maxLogCount;
    int m_maxFileSize;
    QString m_logDir;
};


template <class ObjectType>
struct myLogSourceAPI : public SourceApiMap
{
    myLogSourceAPI(ObjectType *object, const QString &name = QLatin1String("myLog"))
        : SourceApiMap(), m_name(name)
    {
        Q_UNUSED(object);
        m_enums[0] = 0;
        m_properties[0] = 5;
        m_properties[1] = QtPrivate::qtro_property_index<ObjectType>(&ObjectType::heartBeatInterval, static_cast<int (QObject::*)()>(0),"heartBeatInterval");
        QtPrivate::qtro_method_test<ObjectType>(&ObjectType::heartBeatIntervalChanged, static_cast<void (QObject::*)()>(0));
        m_properties[2] = QtPrivate::qtro_property_index<ObjectType>(&ObjectType::isWriteToFile, static_cast<bool (QObject::*)()>(0),"isWriteToFile");
        QtPrivate::qtro_method_test<ObjectType>(&ObjectType::isWriteToFileChanged, static_cast<void (QObject::*)()>(0));
        m_properties[3] = QtPrivate::qtro_property_index<ObjectType>(&ObjectType::maxLogCount, static_cast<int (QObject::*)()>(0),"maxLogCount");
        QtPrivate::qtro_method_test<ObjectType>(&ObjectType::maxLogCountChanged, static_cast<void (QObject::*)()>(0));
        m_properties[4] = QtPrivate::qtro_property_index<ObjectType>(&ObjectType::maxFileSize, static_cast<int (QObject::*)()>(0),"maxFileSize");
        QtPrivate::qtro_method_test<ObjectType>(&ObjectType::maxFileSizeChanged, static_cast<void (QObject::*)()>(0));
        m_properties[5] = QtPrivate::qtro_property_index<ObjectType>(&ObjectType::logDir, static_cast<QString (QObject::*)()>(0),"logDir");
        QtPrivate::qtro_method_test<ObjectType>(&ObjectType::logDirChanged, static_cast<void (QObject::*)()>(0));
        m_signals[0] = 7;
        m_signals[1] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::heartBeatIntervalChanged, static_cast<void (QObject::*)(int)>(0),m_signalArgCount+0,&m_signalArgTypes[0]);
        m_signals[2] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::isWriteToFileChanged, static_cast<void (QObject::*)(bool)>(0),m_signalArgCount+1,&m_signalArgTypes[1]);
        m_signals[3] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::maxLogCountChanged, static_cast<void (QObject::*)(int)>(0),m_signalArgCount+2,&m_signalArgTypes[2]);
        m_signals[4] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::maxFileSizeChanged, static_cast<void (QObject::*)(int)>(0),m_signalArgCount+3,&m_signalArgTypes[3]);
        m_signals[5] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::logDirChanged, static_cast<void (QObject::*)(QString)>(0),m_signalArgCount+4,&m_signalArgTypes[4]);
        m_signals[6] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::logChanged, static_cast<void (QObject::*)(QString)>(0),m_signalArgCount+5,&m_signalArgTypes[5]);
        m_signals[7] = QtPrivate::qtro_signal_index<ObjectType>(&ObjectType::heartToClient, static_cast<void (QObject::*)(qint64)>(0),m_signalArgCount+6,&m_signalArgTypes[6]);
        m_methods[0] = 6;
        m_methods[1] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::pushHeartBeatInterval, static_cast<void (QObject::*)(int)>(0),"pushHeartBeatInterval(int)",m_methodArgCount+0,&m_methodArgTypes[0]);
        m_methods[2] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::pushIsWriteToFile, static_cast<void (QObject::*)(bool)>(0),"pushIsWriteToFile(bool)",m_methodArgCount+1,&m_methodArgTypes[1]);
        m_methods[3] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::pushMaxLogCount, static_cast<void (QObject::*)(int)>(0),"pushMaxLogCount(int)",m_methodArgCount+2,&m_methodArgTypes[2]);
        m_methods[4] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::pushMaxFileSize, static_cast<void (QObject::*)(int)>(0),"pushMaxFileSize(int)",m_methodArgCount+3,&m_methodArgTypes[3]);
        m_methods[5] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::pushLogDir, static_cast<void (QObject::*)(QString)>(0),"pushLogDir(QString)",m_methodArgCount+4,&m_methodArgTypes[4]);
        m_methods[6] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::exitServer, static_cast<void (QObject::*)()>(0),"exitServer()",m_methodArgCount+5,&m_methodArgTypes[5]);
    }

    QString name() const override { return m_name; }
    QString typeName() const override { return QStringLiteral("myLog"); }
    int enumCount() const override { return m_enums[0]; }
    int propertyCount() const override { return m_properties[0]; }
    int signalCount() const override { return m_signals[0]; }
    int methodCount() const override { return m_methods[0]; }
    int sourceEnumIndex(int index) const override
    {
        if (index < 0 || index >= m_enums[0])
            return -1;
        return m_enums[index+1];
    }
    int sourcePropertyIndex(int index) const override
    {
        if (index < 0 || index >= m_properties[0])
            return -1;
        return m_properties[index+1];
    }
    int sourceSignalIndex(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return -1;
        return m_signals[index+1];
    }
    int sourceMethodIndex(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return -1;
        return m_methods[index+1];
    }
    int signalParameterCount(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return -1;
        return m_signalArgCount[index];
    }
    int signalParameterType(int sigIndex, int paramIndex) const override
    {
        if (sigIndex < 0 || sigIndex >= m_signals[0] || paramIndex < 0 || paramIndex >= m_signalArgCount[sigIndex])
            return -1;
        return m_signalArgTypes[sigIndex][paramIndex];
    }
    int methodParameterCount(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return -1;
        return m_methodArgCount[index];
    }
    int methodParameterType(int methodIndex, int paramIndex) const override
    {
        if (methodIndex < 0 || methodIndex >= m_methods[0] || paramIndex < 0 || paramIndex >= m_methodArgCount[methodIndex])
            return -1;
        return m_methodArgTypes[methodIndex][paramIndex];
    }
    int propertyIndexFromSignal(int index) const override
    {
        switch (index) {
        case 0: return m_properties[1];
        case 1: return m_properties[2];
        case 2: return m_properties[3];
        case 3: return m_properties[4];
        case 4: return m_properties[5];
        }
        return -1;
    }
    int propertyRawIndexFromSignal(int index) const override
    {
        switch (index) {
        case 0: return 0;
        case 1: return 1;
        case 2: return 2;
        case 3: return 3;
        case 4: return 4;
        }
        return -1;
    }
    const QByteArray signalSignature(int index) const override
    {
        switch (index) {
        case 0: return QByteArrayLiteral("heartBeatIntervalChanged(int)");
        case 1: return QByteArrayLiteral("isWriteToFileChanged(bool)");
        case 2: return QByteArrayLiteral("maxLogCountChanged(int)");
        case 3: return QByteArrayLiteral("maxFileSizeChanged(int)");
        case 4: return QByteArrayLiteral("logDirChanged(QString)");
        case 5: return QByteArrayLiteral("logChanged(QString)");
        case 6: return QByteArrayLiteral("heartToClient(qint64)");
        }
        return QByteArrayLiteral("");
    }
    QList<QByteArray> signalParameterNames(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return QList<QByteArray>();
        return ObjectType::staticMetaObject.method(m_signals[index + 1]).parameterNames();
    }
    const QByteArray methodSignature(int index) const override
    {
        switch (index) {
        case 0: return QByteArrayLiteral("pushHeartBeatInterval(int)");
        case 1: return QByteArrayLiteral("pushIsWriteToFile(bool)");
        case 2: return QByteArrayLiteral("pushMaxLogCount(int)");
        case 3: return QByteArrayLiteral("pushMaxFileSize(int)");
        case 4: return QByteArrayLiteral("pushLogDir(QString)");
        case 5: return QByteArrayLiteral("exitServer()");
        }
        return QByteArrayLiteral("");
    }
    QMetaMethod::MethodType methodType(int) const override
    {
        return QMetaMethod::Slot;
    }
    QList<QByteArray> methodParameterNames(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return QList<QByteArray>();
        return ObjectType::staticMetaObject.method(m_methods[index + 1]).parameterNames();
    }
    const QByteArray typeName(int index) const override
    {
        switch (index) {
        case 0: return QByteArrayLiteral("void");
        case 1: return QByteArrayLiteral("void");
        case 2: return QByteArrayLiteral("void");
        case 3: return QByteArrayLiteral("void");
        case 4: return QByteArrayLiteral("void");
        case 5: return QByteArrayLiteral("void");
        }
        return QByteArrayLiteral("");
    }
    QByteArray objectSignature() const override { return QByteArray{"82622c9d66c741d23b058105a0bab9bd13df9a9a"}; }

    int m_enums[1];
    int m_properties[6];
    int m_signals[8];
    int m_methods[7];
    const QString m_name;
    int m_signalArgCount[7];
    const int* m_signalArgTypes[7];
    int m_methodArgCount[6];
    const int* m_methodArgTypes[6];
};

QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // REP_MYLOG_SOURCE_H
